# .github/workflows/terraform-deploy.yml
name: Terraform Deploy

# Manual trigger; user chooses "apply" or "destroy"
'on':
  workflow_dispatch:
    inputs:
      action:
        description: Terraform action
        required: true
        default: apply
        type: choice
        options: [apply, destroy]

# Only the permissions needed for this file (no OIDC)
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1                # adjust if needed
      TF_IN_AUTOMATION: "true"                     # nicer CI output

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1                 # pin for reproducibility

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform ${{ github.event.inputs.action }}
        run: >
          terraform
          ${{ github.event.inputs.action }}
          -auto-approve
