# .github/workflows/uc-05-deploy.yml
# UC‑05 – streamlined Terraform workflow (no TFLint / Checkov)
name: UC-05 Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action"
        required: true
        default: apply
        type: choice
        options: [apply, destroy]

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.6.6"
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      # 0️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 1️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 2️⃣ Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767397779454:role/oidc-assume-role
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Optional policy simulator (can be removed later)
      - name: Simulate IAM permissions
        run: |
          aws iam simulate-principal-policy \
            --policy-source-arn arn:aws:iam::767397779454:role/oidc-assume-role \
            --action-names s3:CreateBucket sns:CreateTopic iam:CreateRole lambda:CreateFunction

      # 4️⃣ Terraform workflow
      - name: Terraform FMT (check only)
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'apply'
        run: |
          terraform plan \
            -var-file="terraform.tfvars" \
            -lock-timeout=30s \
            -input=false \
            -out=tfplan.binary

      - name: Show Plan Summary
        if: github.event.inputs.action == 'apply'
        run: terraform show -no-color tfplan.binary

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan.binary

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
